version: "3.9"

services:
  gestorincidentes:
    build:
      context: ./GestorIncidentes
    ports:
      - "5001:5000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=database-1.cnyu44uss058.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=postgres

    networks:
      - backend

networks:
  backend:
    driver: bridge
